import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { LanguageProvider } from "@/context/LanguageContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "LinguaAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <LanguageProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <NavBar />
              {children}
            </body>
      </LanguageProvider>
    </html>
  );
}
